import {MainNavigationItem, TabsData, TabsItem} from './interfaces';

export const mainNavigationList: MainNavigationItem[] = [
  {url: '/account', name: 'Account'},
  {url: '/profile', name: 'Profile'},
]

export const accountTabs: TabsItem[] = [
  {
    ariaLabel: 'To open transactions tab',
    ariaControls: 'transactions-tab',
    id: 'transactions',
    name: 'account transactions',
    active: true,
  },
  {
    ariaLabel: 'To open bank statements tab',
    ariaControls: 'statements-tab',
    id: 'statements',
    name: 'bank statements',
    active: false,
  },
]

export const accountTransactionsTabsData: TabsData = {
  tableData: [
    {
      status: 'Processing',
      description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'positive',
    },
    {
      status: 'Pending',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi
       exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    },
    {
      status: 'Authorized',
      description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'positive',
    },
    {
      status: 'Pending / Hold',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    },
    {
      status: 'Pending',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    },
    {
      status: 'Authorized',
      description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'positive',
    },
    {
      status: 'Pending / Hold',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    }, {
      status: 'Pending',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    },
    {
      status: 'Authorized',
      description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'positive',
    },
    {
      status: 'Pending / Hold',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    }, {
      status: 'Pending',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    },
    {
      status: 'Authorized',
      description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'positive',
    },
    {
      status: 'Pending / Hold',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    }, {
      status: 'Pending',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    },
    {
      status: 'Authorized',
      description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'positive',
    },
    {
      status: 'Pending / Hold',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    }, {
      status: 'Pending',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    },
    {
      status: 'Authorized',
      description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'positive',
    },
    {
      status: 'Pending / Hold',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    }, {
      status: 'Pending',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    },
    {
      status: 'Authorized',
      description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'positive',
    },
    {
      status: 'Pending / Hold',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    }, {
      status: 'Pending',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    },
    {
      status: 'Authorized',
      description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'positive',
    },
    {
      status: 'Pending / Hold',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    }, {
      status: 'Pending',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    },
    {
      status: 'Authorized',
      description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'positive',
    },
    {
      status: 'Pending / Hold',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    }, {
      status: 'Pending',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    },
    {
      status: 'Authorized',
      description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'positive',
    },
    {
      status: 'Pending / Hold',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    }, {
      status: 'Pending',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    },
    {
      status: 'Authorized',
      description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'positive',
    },
    {
      status: 'Pending / Hold',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    }, {
      status: 'Pending',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    },
    {
      status: 'Authorized',
      description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'positive',
    },
    {
      status: 'Pending / Hold',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    }, {
      status: 'Pending',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    },
    {
      status: 'Authorized',
      description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'positive',
    },
    {
      status: 'Pending / Hold',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    }, {
      status: 'Pending',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    },
    {
      status: 'Authorized',
      description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'positive',
    },
    {
      status: 'Pending / Hold',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    }, {
      status: 'Pending',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    },
    {
      status: 'Authorized',
      description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'positive',
    },
    {
      status: 'Pending / Hold',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    }, {
      status: 'Pending',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    },
    {
      status: 'Authorized',
      description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'positive',
    },
    {
      status: 'Pending / Hold',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    }, {
      status: 'Pending',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    },
    {
      status: 'Authorized',
      description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'positive',
    },
    {
      status: 'Pending / Hold',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    }, {
      status: 'Pending',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    },
    {
      status: 'Authorized',
      description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'positive',
    },
    {
      status: 'Pending / Hold',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    }, {
      status: 'Pending',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    },
    {
      status: 'Authorized',
      description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'positive',
    },
    {
      status: 'Pending / Hold',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    }, {
      status: 'Pending',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    },
    {
      status: 'Authorized',
      description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'positive',
    },
    {
      status: 'Pending / Hold',
      description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
      check: '383931',
      returnData: '01',
      tCode: 'POS',
      amount: '999,999,999.99',
      balance: 'negative',
    },
  ],
  tableActions: [
    {title: 'Action 0'},
    {title: 'Action 1'},
    {title: 'Action 2'},
    {title: 'Delete'}
  ],
  tableFilter: [
    {title: 'Status'},
    {title: 'Description'},
    {title: 'Check'},
    {title: 'Return'},
    {title: 'T-Code'},
    {title: 'Amount'},
    {title: 'Balance'},
  ]
}

export const accountStatementsTabsData: TabsData = {
  tableData: [],
  tableActions: [],
  tableFilter: []
}
