export const transactionTableHeads = [
  {title: 'Status #'},
  {title: 'Description'},
  {title: 'Check'},
  {title: 'Return'},
  {title: 'T-Code'},
  {title: 'Amount'},
  {title: 'Balance', notSort: true},
]

export const transactionTableData = [
  {
    status: 'Processing',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'positive',
  },
  {
    status: 'Pending',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },
  {
    status: 'Authorized',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'positive',
  },
  {
    status: 'Pending / Hold',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },
  {
    status: 'Pending',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },
  {
    status: 'Authorized',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'positive',
  },
  {
    status: 'Pending / Hold',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },{
    status: 'Pending',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },
  {
    status: 'Authorized',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'positive',
  },
  {
    status: 'Pending / Hold',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },{
    status: 'Pending',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },
  {
    status: 'Authorized',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'positive',
  },
  {
    status: 'Pending / Hold',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },{
    status: 'Pending',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },
  {
    status: 'Authorized',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'positive',
  },
  {
    status: 'Pending / Hold',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },{
    status: 'Pending',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },
  {
    status: 'Authorized',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'positive',
  },
  {
    status: 'Pending / Hold',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },{
    status: 'Pending',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },
  {
    status: 'Authorized',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'positive',
  },
  {
    status: 'Pending / Hold',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },{
    status: 'Pending',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },
  {
    status: 'Authorized',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'positive',
  },
  {
    status: 'Pending / Hold',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },{
    status: 'Pending',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },
  {
    status: 'Authorized',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'positive',
  },
  {
    status: 'Pending / Hold',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },{
    status: 'Pending',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },
  {
    status: 'Authorized',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'positive',
  },
  {
    status: 'Pending / Hold',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },{
    status: 'Pending',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },
  {
    status: 'Authorized',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'positive',
  },
  {
    status: 'Pending / Hold',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },{
    status: 'Pending',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },
  {
    status: 'Authorized',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'positive',
  },
  {
    status: 'Pending / Hold',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },{
    status: 'Pending',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },
  {
    status: 'Authorized',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'positive',
  },
  {
    status: 'Pending / Hold',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },{
    status: 'Pending',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },
  {
    status: 'Authorized',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'positive',
  },
  {
    status: 'Pending / Hold',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },{
    status: 'Pending',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },
  {
    status: 'Authorized',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'positive',
  },
  {
    status: 'Pending / Hold',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },{
    status: 'Pending',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },
  {
    status: 'Authorized',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'positive',
  },
  {
    status: 'Pending / Hold',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },{
    status: 'Pending',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },
  {
    status: 'Authorized',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'positive',
  },
  {
    status: 'Pending / Hold',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },{
    status: 'Pending',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },
  {
    status: 'Authorized',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'positive',
  },
  {
    status: 'Pending / Hold',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },{
    status: 'Pending',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },
  {
    status: 'Authorized',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'positive',
  },
  {
    status: 'Pending / Hold',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },{
    status: 'Pending',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },
  {
    status: 'Authorized',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit.`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'positive',
  },
  {
    status: 'Pending / Hold',
    description: ` A ab ad amet at atque consequatur doloremque ducimus enim eos excepturi exercitationem impedit maiores maxime molestias possimus quia rerum tempora, voluptatem!`,
    check: '383931',
    returnData: '01',
    tCode: 'POS',
    amount: '999,999,999.99',
    balance: 'negative',
  },
]

export const transactionTableActions = [
  {title: 'Action 0'},
  {title: 'Action 1'},
  {title: 'Action 2'},
  {title: 'Delete'}
]

export const transactionTableFilter = [...transactionTableHeads]
